sims:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/SimController.php'

agent_com:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/AgentComController.php'

offres:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/OffreController.php'

marques:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/MarqueController.php'

sim:
    resource: "@SimBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
