<?php

namespace SimBundle\Repository;

/**
 * CinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinRepository extends \Doctrine\ORM\EntityRepository
{
}
